exec-once = $bar
exec-once = $wallpaper
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Open apps in dedicated workspaces
exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 2 silent] $terminal
exec-once = [workspace 3 silent] $browser
exec-once = [workspace 9 silent] sleep 5 && $music
