# Hyprpaper configuration

wallpaper {
    monitor = DP-1
    path = /home/matan/.config/wallpapers/2k/purple_sword.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/matan/.config/wallpapers/1080/chill_house.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-3
    path = /home/matan/.config/wallpapers/2k/purple_sword.png
    fit_mode = cover
}
