# Set programs that you use
$terminal = kitty
$browser = firefox
$browser2 = qutebrowser
$fileManager = dolphin
$wallpaper = /home/matan/dev/dotfiles/scripts/set-wallpaper.sh
# $wallpaper = ~/.local/bin/wpaperd -d
$menu = wofi --show drun --columns 1
$bar = qs -c noctalia-shell
$copy = cliphist list | wofi -S dmenu | cliphist decode | wl-copy
$music = spotify-launcher
