# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
workspace = 1, monitor:HDMI-A-3, default:true
workspace = 2, monitor:HDMI-A-3
workspace = 3, monitor:HDMI-A-3
workspace = 4, monitor:HDMI-A-3
workspace = 5, monitor:HDMI-A-3
workspace = 6, monitor:HDMI-A-3
workspace = 7, monitor:HDMI-A-3
workspace = 8, monitor:HDMI-A-3
workspace = 9, monitor:HDMI-A-3

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule = workspace 9, match:class spotify
